packages:
  - "apps/*"
  - "packages/*"
overrides:
  shell-quote: 1.10.0
  sharp: 0.35.3
allowBuilds:
  better-sqlite3: true
  electron: true
  esbuild: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
