// Generated by @aurascholar/tokens build script — do not edit.
export const themes = {
  "dawn": {
    "color-bg": "#f8f7f3",
    "color-bg-subtle": "#fdfdfb",
    "color-surface": "#fdfdfb",
    "color-surface-raised": "#ffffff",
    "color-surface-sunken": "#efede6",
    "color-border": "#e3e0d6",
    "color-border-strong": "#c9c5b8",
    "color-text": "#1a1a18",
    "color-text-secondary": "#3d3c38",
    "color-text-muted": "#6b6a63",
    "color-text-faint": "#9b9a92",
    "color-accent": "#4d837d",
    "color-accent-strong": "#3d6b66",
    "color-accent-subtle": "#e8f0ef",
    "color-accent-contrast": "#ffffff",
    "color-danger": "#b4453c",
    "color-warning": "#a3742b",
    "color-success": "#4a7c50",
    "color-selection": "rgba(77, 131, 125, 0.18)",
    "font-heading": "\"Source Serif 4\", \"Source Han Serif SC\", \"Noto Serif SC\", Georgia, serif",
    "font-body": "\"Inter\", \"PingFang SC\", \"Noto Sans SC\", -apple-system, sans-serif",
    "font-mono": "\"JetBrains Mono\", \"SF Mono\", Menlo, Consolas, monospace",
    "radius-card": "12px",
    "radius-control": "8px",
    "radius-pill": "9999px",
    "shadow-card": "0 1px 3px rgba(26, 26, 24, 0.06), 0 1px 2px rgba(26, 26, 24, 0.04)",
    "shadow-overlay": "0 8px 30px rgba(26, 26, 24, 0.12)",
    "border-width": "1px",
    "glow-accent": "none"
  },
  "nocturne": {
    "color-bg": "#0a0c10",
    "color-bg-subtle": "#0f1218",
    "color-surface": "#0f1218",
    "color-surface-raised": "#161b24",
    "color-surface-sunken": "#0a0c10",
    "color-border": "#1f2632",
    "color-border-strong": "#2c3545",
    "color-text": "#d6dde8",
    "color-text-secondary": "#aab4c4",
    "color-text-muted": "#566073",
    "color-text-faint": "#2c3545",
    "color-accent": "#22d3ee",
    "color-accent-strong": "#4be0f5",
    "color-accent-subtle": "rgba(34, 211, 238, 0.12)",
    "color-accent-contrast": "#0a0c10",
    "color-danger": "#f87171",
    "color-warning": "#fbbf24",
    "color-success": "#4ade80",
    "color-selection": "rgba(34, 211, 238, 0.22)",
    "font-heading": "\"Inter\", \"PingFang SC\", \"Noto Sans SC\", -apple-system, sans-serif",
    "font-body": "\"Inter\", \"PingFang SC\", \"Noto Sans SC\", -apple-system, sans-serif",
    "font-mono": "\"JetBrains Mono\", \"SF Mono\", Menlo, Consolas, monospace",
    "radius-card": "8px",
    "radius-control": "4px",
    "radius-pill": "9999px",
    "shadow-card": "0 0 0 1px rgba(34, 211, 238, 0.06), 0 4px 16px rgba(0, 0, 0, 0.5)",
    "shadow-overlay": "0 0 24px rgba(34, 211, 238, 0.15), 0 8px 40px rgba(0, 0, 0, 0.7)",
    "border-width": "1px",
    "glow-accent": "0 0 12px rgba(34, 211, 238, 0.4)"
  }
} as const;
export type ThemeName = keyof typeof themes;
export type TokenName = keyof (typeof themes)["dawn"];
export const themeNames = ["dawn","nocturne"] as const;
export const highlightColors = {
  "yellow": "#ffd866",
  "green": "#a9dc76",
  "blue": "#78dce8",
  "pink": "#ff6188",
  "purple": "#ab9df2",
  "orange": "#fc9867"
} as const;
export type HighlightColor = keyof typeof highlightColors;
