// Generates dist/tokens.css (CSS custom properties per theme) and src/generated.ts
// (TS constants for canvas/WebGL consumers that cannot read CSS variables).
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const primitives = JSON.parse(readFileSync(join(root, "src/primitives.json"), "utf8"));
const themes = JSON.parse(readFileSync(join(root, "src/themes.json"), "utf8"));

function resolveRef(value) {
  if (typeof value !== "string") return value;
  return value.replace(/\{([^}]+)\}/g, (_, path) => {
    const resolved = path.split(".").reduce((obj, key) => obj?.[key], primitives);
    if (resolved === undefined) throw new Error(`Unknown token reference: {${path}}`);
    return resolved;
  });
}

function primitiveCssVars() {
  const entries = [];
  for (const [key, value] of Object.entries(primitives.size.space)) {
    entries.push([`space-${key}`, value]);
  }
  for (const [key, value] of Object.entries(primitives.size.radius)) {
    entries.push([`radius-${key}`, value]);
  }
  for (const [key, value] of Object.entries(primitives.color.highlight)) {
    entries.push([`color-highlight-${key}`, value]);
  }
  return entries;
}

const themeNames = Object.keys(themes);
const resolved = {};
for (const name of themeNames) {
  resolved[name] = Object.fromEntries(
    Object.entries(themes[name]).map(([k, v]) => [k, resolveRef(v)]),
  );
}

// All themes must define the same token set — a missing token would silently
// fall through to the other theme's value after a theme switch.
const [first, ...rest] = themeNames;
const firstKeys = JSON.stringify(Object.keys(resolved[first]).sort());
for (const name of rest) {
  if (JSON.stringify(Object.keys(resolved[name]).sort()) !== firstKeys) {
    throw new Error(`Theme "${name}" token keys do not match theme "${first}"`);
  }
}

let css = `/* Generated by @aurascholar/tokens — do not edit. */\n`;
css += `\n:root {\n`;
for (const [key, value] of primitiveCssVars()) {
  css += `  --${key}: ${value};\n`;
}
css += `}\n`;
for (const name of themeNames) {
  const selector =
    name === first ? `:root, [data-theme="${name}"]` : `[data-theme="${name}"]`;
  css += `\n${selector} {\n`;
  for (const [key, value] of Object.entries(resolved[name])) {
    css += `  --${key}: ${value};\n`;
  }
  css += `}\n`;
}

mkdirSync(join(root, "dist"), { recursive: true });
writeFileSync(join(root, "dist/tokens.css"), css);

const ts = `// Generated by @aurascholar/tokens build script — do not edit.
export const themes = ${JSON.stringify(resolved, null, 2)} as const;
export type ThemeName = keyof typeof themes;
export type TokenName = keyof (typeof themes)["${first}"];
export const themeNames = ${JSON.stringify(themeNames)} as const;
export const highlightColors = ${JSON.stringify(primitives.color.highlight, null, 2)} as const;
export type HighlightColor = keyof typeof highlightColors;
`;
writeFileSync(join(root, "src/generated.ts"), ts);
console.log(`tokens: built ${themeNames.length} themes → dist/tokens.css, src/generated.ts`);
