// Static homepage renderer: Profile → self-contained HTML (inline CSS, no
// build deps, no external requests). Two templates mirroring the app themes.
import { formatGbt7714, type Profile, type ProfileLink, type ProfilePublication } from "./model";

export interface RenderedSite {
  /** Filename → content. Currently a single index.html; assets may join later. */
  files: Map<string, string>;
}

export function renderSite(profile: Profile): RenderedSite {
  const html = profile.theme === "nocturne-geek" ? renderNocturne(profile) : renderDawn(profile);
  return { files: new Map([["index.html", html]]) };
}

const esc = (s: string) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

const SAFE_LINK_PROTOCOLS = new Set(["http:", "https:", "mailto:"]);

function safeLinkHref(rawUrl: string): string | null {
  const trimmed = rawUrl.trim();
  if (!trimmed) return null;
  try {
    const url = new URL(trimmed);
    return SAFE_LINK_PROTOCOLS.has(url.protocol) ? url.toString() : null;
  } catch {
    return null;
  }
}

function profileLinkAnchor(link: ProfileLink): string | null {
  const href = safeLinkHref(link.url);
  if (!href) return null;
  const target = href.startsWith("mailto:") ? "" : ' target="_blank"';
  return `<a href="${esc(href)}"${target} rel="noopener noreferrer">${esc(link.label)}</a>`;
}

function publicationLi(pub: ProfilePublication): string {
  let line = esc(formatGbt7714(pub));
  if (pub.selfName) {
    const escaped = esc(pub.selfName).replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    line = line.replace(new RegExp(escaped, "g"), `<strong>${esc(pub.selfName)}</strong>`);
  }
  const doi = pub.doi
    ? ` <a href="https://doi.org/${esc(pub.doi)}" target="_blank" rel="noopener noreferrer">[DOI]</a>`
    : "";
  const tags = (pub.tags ?? [])
    .map((t) => `<span class="tag">${esc(t)}</span>`)
    .join(" ");
  return `<li>${line}${doi} ${tags}</li>`;
}

function commonBody(p: Profile): string {
  const links = p.links
    .map(profileLinkAnchor)
    .filter((anchor): anchor is string => Boolean(anchor));
  const email = p.email?.trim();
  const navLinks = [
    ...links,
    ...(email ? [`<a href="mailto:${esc(email)}">${esc(email)}</a>`] : []),
  ].join('<span class="sep">·</span>');
  const pubs = p.publications.map(publicationLi).join("\n");
  const sections = p.sections
    .filter((s) => s.items.length > 0)
    .map(
      (s) => `
  <section>
    <h2>${esc(s.title)}</h2>
    <ul class="timeline">
      ${s.items
        .map(
          (item) => `<li>
        ${item.period ? `<span class="period">${esc(item.period)}</span>` : ""}
        <div><div class="headline">${esc(item.headline)}</div>
        ${item.detail ? `<div class="detail">${esc(item.detail)}</div>` : ""}</div>
      </li>`,
        )
        .join("\n")}
    </ul>
  </section>`,
    )
    .join("\n");

  return `
  <header>
    <h1>${esc(p.displayName)}</h1>
    ${p.tagline ? `<p class="tagline">${esc(p.tagline)}</p>` : ""}
    <nav class="links">${navLinks}</nav>
  </header>
  ${p.bioMd ? `<section><p class="bio">${esc(p.bioMd)}</p></section>` : ""}
  ${p.publications.length ? `<section><h2>发表论文</h2><ol class="pubs" reversed>${pubs}</ol></section>` : ""}
  ${sections}
  <footer>Generated by <a href="https://github.com/aurascholar/aurascholar" rel="noopener noreferrer">AuraScholar</a></footer>`;
}

function renderDawn(p: Profile): string {
  return `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(p.displayName)}</title>
<style>
:root{--bg:#f8f7f3;--surface:#fdfdfb;--text:#1a1a18;--muted:#6b6a63;--accent:#4d837d;--border:#e3e0d6}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:16px/1.7 Georgia,"Source Han Serif SC","Noto Serif SC",serif;display:flex;justify-content:center;padding:48px 20px}
main{max-width:760px;width:100%}
h1{font-size:34px;font-weight:600;margin:0 0 4px}
.tagline{color:var(--muted);margin:0 0 12px;font-size:15px}
.links a{color:var(--accent);text-decoration:none;font-size:14px}
.links a:hover{text-decoration:underline}.sep{color:var(--border);margin:0 8px}
h2{font-size:20px;margin:36px 0 12px;border-bottom:1px solid var(--border);padding-bottom:6px;font-weight:600}
.bio{color:var(--text);font-size:15px}
.pubs{padding-left:22px}.pubs li{margin-bottom:10px;font-size:15px}
.pubs a{color:var(--accent);text-decoration:none}
.tag{display:inline-block;font:12px/1.6 -apple-system,sans-serif;background:#e8f0ef;color:#3d6b66;border-radius:99px;padding:0 9px;margin-left:4px}
.timeline{list-style:none;padding:0}.timeline li{display:flex;gap:16px;margin-bottom:12px;font-size:15px}
.period{color:var(--muted);min-width:130px;flex-shrink:0;font-size:13.5px;font-family:-apple-system,sans-serif;padding-top:2px}
.headline{font-weight:600}.detail{color:var(--muted);font-size:14px}
footer{margin-top:56px;color:var(--muted);font-size:12.5px;font-family:-apple-system,sans-serif}
footer a{color:var(--accent)}
</style></head><body><main>${commonBody(p)}</main></body></html>`;
}

function renderNocturne(p: Profile): string {
  return `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(p.displayName)}</title>
<style>
:root{--bg:#0a0c10;--surface:#0f1218;--text:#d6dde8;--muted:#566073;--accent:#22d3ee;--border:#1f2632}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:15px/1.7 "Inter","PingFang SC",-apple-system,sans-serif;display:flex;justify-content:center;padding:48px 20px}
main{max-width:760px;width:100%}
h1{font-size:32px;font-weight:700;margin:0 0 4px;letter-spacing:-.5px}
h1::after{content:"_";color:var(--accent);animation:blink 1.2s step-end infinite}
@keyframes blink{50%{opacity:0}}
.tagline{color:var(--muted);margin:0 0 12px;font-size:14px;font-family:"JetBrains Mono",monospace}
.links a{color:var(--accent);text-decoration:none;font-size:13.5px;font-family:"JetBrains Mono",monospace}
.links a:hover{text-shadow:0 0 8px rgba(34,211,238,.6)}.sep{color:var(--border);margin:0 8px}
h2{font-size:17px;margin:36px 0 12px;font-family:"JetBrains Mono",monospace;color:var(--accent)}
h2::before{content:"# ";color:var(--muted)}
.bio{font-size:14.5px}
.pubs{padding-left:22px}.pubs li{margin-bottom:10px;font-size:14px}
.pubs a{color:var(--accent);text-decoration:none}
.tag{display:inline-block;font-size:11.5px;border:1px solid var(--accent);color:var(--accent);border-radius:3px;padding:0 7px;margin-left:4px}
.timeline{list-style:none;padding:0}.timeline li{display:flex;gap:16px;margin-bottom:12px;font-size:14px}
.period{color:var(--muted);min-width:130px;flex-shrink:0;font-size:12.5px;font-family:"JetBrains Mono",monospace;padding-top:2px}
.headline{font-weight:600;color:#aab4c4}.detail{color:var(--muted);font-size:13px}
footer{margin-top:56px;color:var(--muted);font-size:12px;font-family:"JetBrains Mono",monospace}
footer a{color:var(--accent)}
</style></head><body><main>${commonBody(p)}</main></body></html>`;
}
