import {
  assertGroundingPack,
  assertGroundingPackShape,
  resolveGroundingCitation,
  toGroundingCitationProjection,
  type GroundingCitationProjection,
} from "./grounding-pack-validation.js";
import {
  type GroundingCoverageState,
  type GroundingPack,
  type GroundingPackItem,
} from "./grounding-pack.js";

/** Versioned structured output accepted from an optional generation provider. */
export const GROUNDING_ANSWER_VERSION = 1 as const;
export const GROUNDING_CLAIM_KINDS = ["factual", "interpretive", "uncertain"] as const;
export type GroundingClaimKind = (typeof GROUNDING_CLAIM_KINDS)[number];
export const GROUNDING_ANSWER_STATUSES = ["answer", "insufficient", "conflicting"] as const;
export type GroundingAnswerStatus = (typeof GROUNDING_ANSWER_STATUSES)[number];

/** Relations are resolver-owned metadata, never fields supplied by a model. */
export const GROUNDING_CLAIM_RELATIONS = [
  "supports",
  "qualifies",
  "contradicts",
  "background",
] as const;
export type GroundingClaimRelation = (typeof GROUNDING_CLAIM_RELATIONS)[number];

export const MAX_GROUNDING_ANSWER_CHARS = 64 * 1024;
export const MAX_GROUNDING_CLAIMS = 64;
export const MAX_GROUNDING_CLAIM_CHARS = 8 * 1024;
export const MAX_GROUNDING_CLAIM_KEY_CHARS = 256;
export const MAX_GROUNDING_CITATIONS_PER_CLAIM = 64;
export const MAX_GROUNDING_CITATIONS_PER_ANSWER = 256;

export interface GroundedClaimInput {
  readonly claimKey: string;
  readonly text: string;
  readonly kind: GroundingClaimKind;
  readonly citationIds: readonly string[];
}
export interface GroundedAnswerInput {
  readonly version: typeof GROUNDING_ANSWER_VERSION;
  readonly answerMarkdown: string;
  readonly claims: readonly GroundedClaimInput[];
  readonly status?: GroundingAnswerStatus;
}

export type GroundingClaimRelationMap = Readonly<Record<string, GroundingClaimRelation>>;
export type GroundingClaimRelations = Readonly<
  Record<string, GroundingClaimRelationMap | readonly GroundingClaimRelationInput[]>
>;
export interface GroundingClaimRelationInput {
  readonly citationId: string;
  readonly relation: GroundingClaimRelation;
}
export interface GroundedAnswerValidationOptions {
  /** Trusted relation labels generated by the retrieval/synthesis service. */
  readonly claimRelations?: GroundingClaimRelations;
  readonly relations?: GroundingClaimRelations;
  readonly maxCitationsPerClaim?: number;
  readonly requireCitationMarkers?: boolean;
}

export interface ValidatedGroundedClaim {
  readonly claimKey: string;
  readonly text: string;
  readonly kind: GroundingClaimKind;
  readonly citationIds: readonly string[];
  readonly citationRelations: GroundingClaimRelationMap;
  readonly citations: readonly GroundingCitationProjection[];
  readonly coverage: GroundingCoverageState;
}
export interface ValidatedGroundedAnswer {
  readonly version: typeof GROUNDING_ANSWER_VERSION;
  readonly answerMarkdown: string;
  readonly claims: readonly ValidatedGroundedClaim[];
  readonly status: GroundingAnswerStatus;
  readonly packHash: string;
}

/** Validates model output; source identity is resolved only from pack-issued IDs. */
export function validateGroundedAnswer(
  pack: GroundingPack,
  value: unknown,
  options: GroundedAnswerValidationOptions = {},
): ValidatedGroundedAnswer {
  if (options === null || typeof options !== "object" || Array.isArray(options)) {
    throw new Error("Grounded answer validation options are invalid");
  }
  assertExactKeys(
    options as Record<string, unknown>,
    [],
    ["claimRelations", "relations", "maxCitationsPerClaim", "requireCitationMarkers"],
  );
  if (
    options.requireCitationMarkers !== undefined &&
    typeof options.requireCitationMarkers !== "boolean"
  )
    throw new Error("Grounded answer marker option is invalid");
  if (
    options.claimRelations !== undefined &&
    options.relations !== undefined &&
    options.claimRelations !== options.relations
  )
    throw new Error("Grounded answer relation tables conflict");
  assertGroundingPackShape(pack);
  const answer = parseAnswer(value);
  const answerMarkdown = normalizeCitationMarkers(answer.answerMarkdown);
  assertSafeGroundedMarkdown(answerMarkdown);
  const relationTable = options.claimRelations ?? options.relations ?? {};
  if (relationTable === null || typeof relationTable !== "object" || Array.isArray(relationTable)) {
    throw new Error("Grounded answer relation table is invalid");
  }
  const claimKeys = new Set<string>();
  let citedTotal = 0;
  const claims = answer.claims.map((rawClaim, index) => {
    const claim = parseClaim(rawClaim, index, options.maxCitationsPerClaim);
    citedTotal += claim.citationIds.length;
    if (citedTotal > MAX_GROUNDING_CITATIONS_PER_ANSWER)
      throw new Error(
        `Grounded answer citations are limited to ${MAX_GROUNDING_CITATIONS_PER_ANSWER}`,
      );
    if (claimKeys.has(claim.claimKey))
      throw new Error(`Grounded claim key ${claim.claimKey} is duplicated`);
    claimKeys.add(claim.claimKey);
    const items = claim.citationIds.map((id) => resolveGroundingCitation(pack, id));
    const relations = normalizeClaimRelations(
      relationTable[claim.claimKey],
      claim.citationIds,
      claim.claimKey,
    );
    const coverage = classifyClaimCoverage(items, relations);
    if (
      (claim.kind === "factual" || claim.kind === "interpretive") &&
      claim.citationIds.length === 0
    ) {
      throw new Error(
        `${capitalize(claim.kind)} grounded claim ${claim.claimKey} requires a citation`,
      );
    }
    if (claim.kind === "factual" && coverage === "insufficient-evidence")
      throw new Error(`Factual grounded claim ${claim.claimKey} has no supporting evidence`);
    return {
      claimKey: claim.claimKey,
      text: claim.text,
      kind: claim.kind,
      citationIds: Object.freeze([...claim.citationIds]),
      citationRelations: freezeRecord(relations),
      citations: Object.freeze(items.map(toGroundingCitationProjection)),
      coverage,
    } satisfies ValidatedGroundedClaim;
  });
  for (const key of Object.keys(relationTable)) {
    if (!claimKeys.has(key)) throw new Error(`Grounded relation references unknown claim ${key}`);
  }
  const status = classifyAnswerStatus(claims);
  if (answer.status !== undefined && answer.status !== status)
    throw new Error("Grounded answer status does not match its validated citations");
  assertCitationMarkers(answerMarkdown, claims, pack, options.requireCitationMarkers === true);
  return deepFreeze({
    version: GROUNDING_ANSWER_VERSION,
    answerMarkdown,
    claims: Object.freeze(claims),
    status,
    packHash: pack.hash,
  });
}

export async function validateGroundedAnswerAsync(
  pack: GroundingPack,
  value: unknown,
  options: GroundedAnswerValidationOptions = {},
): Promise<ValidatedGroundedAnswer> {
  await assertGroundingPack(pack);
  return validateGroundedAnswer(pack, value, options);
}
export const validateGroundedOutput = validateGroundedAnswer;
export const validateGroundedOutputAsync = validateGroundedAnswerAsync;

/** Computes coverage from trusted claim-bound relations, never pack-wide labels. */
export function classifyClaimCoverage(
  items: readonly GroundingPackItem[],
  relations: ReadonlyMap<string, GroundingClaimRelation> | GroundingClaimRelationMap = new Map(),
): GroundingCoverageState {
  const supportingSources = new Set<string>();
  let qualifying = 0;
  let contradicting = 0;
  for (const item of items) {
    const relation =
      relations instanceof Map
        ? relations.get(item.citationId)
        : (relations as GroundingClaimRelationMap)[item.citationId];
    if (relation === "supports") {
      for (const sourceId of item.sourceIds) supportingSources.add(sourceId);
    } else if (relation === "qualifies") qualifying += 1;
    else if (relation === "contradicts") contradicting += 1;
  }
  if (contradicting > 0 && (supportingSources.size > 0 || qualifying > 0))
    return "conflicting-sources";
  if (supportingSources.size >= 2) return "multiple-supporting-sources";
  if (supportingSources.size > 0 || qualifying > 0) return "partial-support";
  if (contradicting > 0) return "conflicting-sources";
  return "insufficient-evidence";
}

function parseAnswer(value: unknown): GroundedAnswerInput {
  if (!isRecord(value)) throw new Error("Grounded answer output is invalid");
  // `version` is required for the wire contract; provider status is an
  // optional hint that the service recomputes below.
  if (!Object.hasOwn(value, "version")) throw new Error("Grounded answer version is required");
  assertExactKeys(value, ["version", "answerMarkdown", "claims"], ["status"]);
  if (value.version !== GROUNDING_ANSWER_VERSION)
    throw new Error("Grounded answer version is unsupported");
  const answerMarkdown = requireText(
    value.answerMarkdown,
    "Grounded answer markdown",
    MAX_GROUNDING_ANSWER_CHARS,
    false,
  );
  const claims = value.claims;
  if (!Array.isArray(claims) || claims.length > MAX_GROUNDING_CLAIMS)
    throw new Error(`Grounded answer claims are limited to ${MAX_GROUNDING_CLAIMS}`);
  dense(claims, "Grounded answer claims");
  if (
    value.status !== undefined &&
    !["answer", "insufficient", "conflicting"].includes(value.status as string)
  )
    throw new Error("Grounded answer status is invalid");
  return {
    version: GROUNDING_ANSWER_VERSION,
    answerMarkdown,
    claims: claims as readonly GroundedClaimInput[],
    status: value.status as GroundingAnswerStatus | undefined,
  };
}

function parseClaim(
  value: unknown,
  index: number,
  requestedLimit: number | undefined,
): GroundedClaimInput {
  if (!isRecord(value)) throw new Error(`Grounded claim ${index} is invalid`);
  assertExactKeys(value, ["claimKey", "text", "kind", "citationIds"]);
  const claimKey = requireText(
    value.claimKey,
    `Grounded claim ${index} key`,
    MAX_GROUNDING_CLAIM_KEY_CHARS,
    false,
  );
  if (!/^[A-Za-z0-9][A-Za-z0-9._:-]*$/.test(claimKey))
    throw new Error(`Grounded claim ${index} key is invalid`);
  const text = requireText(
    value.text,
    `Grounded claim ${claimKey} text`,
    MAX_GROUNDING_CLAIM_CHARS,
    false,
  );
  assertSafeGroundedMarkdown(text);
  if (!GROUNDING_CLAIM_KINDS.includes(value.kind as GroundingClaimKind))
    throw new Error(`Grounded claim ${claimKey} kind is invalid`);
  if (!Array.isArray(value.citationIds))
    throw new Error(`Grounded claim ${claimKey} citations are invalid`);
  dense(value.citationIds, `Grounded claim ${claimKey} citations`);
  const limit = requestedLimit ?? MAX_GROUNDING_CITATIONS_PER_CLAIM;
  if (
    !Number.isSafeInteger(limit) ||
    limit < 1 ||
    limit > MAX_GROUNDING_CITATIONS_PER_CLAIM ||
    value.citationIds.length > limit
  )
    throw new Error(`Grounded claim ${claimKey} has too many citations`);
  const ids = value.citationIds.map((id, citationIndex) =>
    normalizeCitationId(id, `Grounded claim ${claimKey} citation ${citationIndex}`),
  );
  if (new Set(ids).size !== ids.length)
    throw new Error(`Grounded claim ${claimKey} citations must be unique`);
  return { claimKey, text, kind: value.kind as GroundingClaimKind, citationIds: ids };
}

function normalizeClaimRelations(
  raw: GroundingClaimRelationMap | readonly GroundingClaimRelationInput[] | undefined,
  citationIds: readonly string[],
  claimKey: string,
): GroundingClaimRelationMap {
  const cited = new Set(citationIds);
  const result: Record<string, GroundingClaimRelation> = {};
  if (raw === undefined) return result;
  if (Array.isArray(raw)) {
    dense(raw, `Grounded claim ${claimKey} relations`);
    const seen = new Set<string>();
    for (const entry of raw) {
      if (!isRecord(entry)) throw new Error("Grounded claim relation is invalid");
      assertExactKeys(entry, ["citationId", "relation"]);
      const citationId = normalizeCitationId(entry.citationId, "Grounded claim relation citation");
      if (!GROUNDING_CLAIM_RELATIONS.includes(entry.relation as GroundingClaimRelation))
        throw new Error("Grounded claim relation is invalid");
      if (seen.has(citationId) || !cited.has(citationId))
        throw new Error("Grounded claim relation references an invalid citation");
      seen.add(citationId);
      result[citationId] = entry.relation as GroundingClaimRelation;
    }
    return result;
  }
  if (!isRecord(raw)) throw new Error(`Grounding claim ${claimKey} relation is invalid`);
  for (const [citationId, relation] of Object.entries(raw)) {
    const id = normalizeCitationId(citationId, `Grounding claim ${claimKey} relation citation`);
    if (!cited.has(id) || !GROUNDING_CLAIM_RELATIONS.includes(relation as GroundingClaimRelation))
      throw new Error(`Grounding claim ${claimKey} relation is invalid`);
    result[id] = relation as GroundingClaimRelation;
  }
  return result;
}

function classifyAnswerStatus(claims: readonly ValidatedGroundedClaim[]): GroundingAnswerStatus {
  if (claims.some((claim) => claim.coverage === "conflicting-sources")) return "conflicting";
  if (claims.length === 0 || claims.every((claim) => claim.coverage === "insufficient-evidence"))
    return "insufficient";
  return "answer";
}

function assertCitationMarkers(
  markdown: string,
  claims: readonly ValidatedGroundedClaim[],
  pack: GroundingPack,
  requireMarkers: boolean,
): void {
  const claimedIds = new Set(claims.flatMap((claim) => claim.citationIds));
  const seen = new Set<string>();
  for (const match of markdown.matchAll(/\b(?:cite|citation):([0-9]+)\b/gi)) {
    const number = match[1]!;
    if (!/^[1-9][0-9]*$/.test(number))
      throw new Error(`Grounded answer marker ${match[0]} is malformed`);
    const id = `cite:${number}`;
    resolveGroundingCitation(pack, id);
    if (!claimedIds.has(id))
      throw new Error(`Grounded answer marker ${id} is not bound to a claim`);
    seen.add(id);
  }
  for (const match of markdown.matchAll(/\b(?:cite|citation):([^\s\])}.,;!?]+)/gi)) {
    if (!/^[0-9]+$/.test(match[1]!))
      throw new Error(`Grounded answer marker ${match[0]} is malformed`);
  }
  if (requireMarkers)
    for (const claim of claims) {
      if (
        (claim.kind === "factual" || claim.kind === "interpretive") &&
        !claim.citationIds.some((id) => seen.has(id))
      )
        throw new Error(`Grounded claim ${claim.claimKey} has no citation marker`);
    }
}

function normalizeCitationMarkers(markdown: string): string {
  return markdown.replace(/\b(?:citation|cite):([1-9][0-9]*)\b/gi, "cite:$1");
}

function assertSafeGroundedMarkdown(value: string): void {
  const lower = value.toLowerCase();
  const unsafePatterns = [
    /<!--[\s\S]*?-->/,
    /<\s*\/?\s*[a-z][^>]*>/,
    /\bon[a-z][\w-]*\s*=/,
    /(?:java|vb)script\s*:/,
    /(?:data|file|blob)\s*:/,
    /!\[[^\]]*\]\(\s*(?:https?:|\/\/|data:)/,
    /\]\(\s*(?:javascript:|vbscript:|data:|file:|blob:)/,
    /\[[^\]]*\]\(\s*[^)]*\)/,
    /^\s*\[[^\]]+\]:\s*\S+/m,
    /<\s*(?:https?:|\/\/|data:|file:|blob:)/,
    /\b(?:src|srcset|href)\s*=\s*["']?\s*(?:https?:|\/\/|data:|file:|blob:|javascript:|vbscript:)/,
    /\b(?:https?|ftp):\/\/[^\s<>()]+/,
    /(?:\u200b|\u200c|\u200d|\ufeff|[\u202a-\u202e])/,
    /&(?:#x?[0-9a-f]+|[a-z][a-z0-9]+);/,
  ];
  if (unsafePatterns.some((pattern) => pattern.test(lower)))
    throw new Error("Grounded answer contains unsafe executable or external content");
}

function normalizeCitationId(value: unknown, label: string): string {
  if (
    typeof value !== "string" ||
    !/^cite:[1-9][0-9]*$/.test(value) ||
    value.length > 64 ||
    containsControl(value)
  )
    throw new Error(`${label} is invalid`);
  return value;
}
function requireText(value: unknown, label: string, maximum: number, allowEmpty: boolean): string {
  if (
    typeof value !== "string" ||
    value.length > maximum ||
    containsControl(value) ||
    (!allowEmpty && !value.trim())
  )
    throw new Error(`${label} is invalid`);
  return value;
}
function assertExactKeys(
  value: Record<string, unknown>,
  required: readonly string[],
  optional: readonly string[] = [],
): void {
  const allowed = new Set([...required, ...optional]);
  if (
    Object.keys(value).some((key) => !allowed.has(key)) ||
    required.some((key) => !Object.hasOwn(value, key))
  )
    throw new Error("Grounded output contains unsupported or missing fields");
}
function dense(value: readonly unknown[], label: string): void {
  for (let index = 0; index < value.length; index += 1)
    if (!Object.hasOwn(value, index)) throw new Error(`${label} must be a dense array`);
}
function containsControl(value: string): boolean {
  for (let index = 0; index < value.length; index += 1) {
    const code = value.charCodeAt(index);
    if ((code <= 0x1f && code !== 0x09 && code !== 0x0a && code !== 0x0d) || code === 0x7f)
      return true;
  }
  return false;
}
function capitalize(value: string): string {
  return value.slice(0, 1).toUpperCase() + value.slice(1);
}
function freezeRecord(value: GroundingClaimRelationMap): GroundingClaimRelationMap {
  return Object.freeze({ ...value });
}
function deepFreeze<T>(value: T): T {
  if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;
  Object.freeze(value);
  for (const child of Object.values(value as Record<string, unknown>)) deepFreeze(child);
  return value;
}
function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
