import {
  assertGroundingPack,
  assertGroundingPackShape,
  resolveGroundingCitation,
  toGroundingCitationProjection,
  type GroundingCitationProjection,
} from "./grounding-pack-validation.js";
import type { GroundingCoverageState, GroundingPack, GroundingPackItem } from "./grounding-pack.js";
import {
  GROUNDING_ANSWER_VERSION,
  GROUNDING_CLAIM_RELATIONS,
  type GroundingAnswerStatus,
  type GroundingClaimKind,
  type GroundingClaimRelation,
  type GroundingClaimRelationInput,
  type GroundingClaimRelationMap,
  type GroundingClaimRelations,
} from "./grounding-output-contract.js";
import { prepareGroundedAnswer } from "./grounding-output-prepare.js";

export {
  GROUNDING_ANSWER_STATUSES,
  GROUNDING_ANSWER_VERSION,
  GROUNDING_CLAIM_KINDS,
  GROUNDING_CLAIM_RELATIONS,
  MAX_GROUNDING_ANSWER_CHARS,
  MAX_GROUNDING_CITATIONS_PER_ANSWER,
  MAX_GROUNDING_CITATIONS_PER_CLAIM,
  MAX_GROUNDING_CLAIM_CHARS,
  MAX_GROUNDING_CLAIM_KEY_CHARS,
  MAX_GROUNDING_CLAIMS,
} from "./grounding-output-contract.js";
export type {
  GroundedAnswerInput,
  GroundedAnswerPreparationOptions,
  GroundedClaimInput,
  GroundingAnswerStatus,
  GroundingClaimKind,
  GroundingClaimRelation,
  GroundingClaimRelationInput,
  GroundingClaimRelationMap,
  GroundingClaimRelations,
} from "./grounding-output-contract.js";
export { prepareGroundedAnswer } from "./grounding-output-prepare.js";

export interface GroundedAnswerValidationOptions {
  /** Trusted relation labels generated by the retrieval/synthesis service. */
  readonly claimRelations?: GroundingClaimRelations;
  readonly relations?: GroundingClaimRelations;
  readonly maxCitationsPerClaim?: number;
  readonly requireCitationMarkers?: boolean;
}

export interface ValidatedGroundedClaim {
  readonly claimKey: string;
  readonly text: string;
  readonly kind: GroundingClaimKind;
  readonly citationIds: readonly string[];
  readonly citationRelations: GroundingClaimRelationMap;
  readonly citations: readonly GroundingCitationProjection[];
  readonly coverage: GroundingCoverageState;
}

export interface ValidatedGroundedAnswer {
  readonly version: typeof GROUNDING_ANSWER_VERSION;
  readonly answerMarkdown: string;
  readonly claims: readonly ValidatedGroundedClaim[];
  readonly status: GroundingAnswerStatus;
  readonly packHash: string;
}

/** Validates model output; source identity is resolved only from pack-issued IDs. */
export function validateGroundedAnswer(
  pack: GroundingPack,
  value: unknown,
  options: GroundedAnswerValidationOptions = {},
): ValidatedGroundedAnswer {
  assertValidationOptions(options);
  assertGroundingPackShape(pack);
  const answer = prepareGroundedAnswer(pack, value, {
    ...(options.maxCitationsPerClaim === undefined
      ? {}
      : { maxCitationsPerClaim: options.maxCitationsPerClaim }),
  });
  const relationTable = options.claimRelations ?? options.relations ?? {};
  if (relationTable === null || typeof relationTable !== "object" || Array.isArray(relationTable)) {
    throw new Error("Grounded answer relation table is invalid");
  }
  const claimKeys = new Set<string>();
  const claims = answer.claims.map((claim) => {
    claimKeys.add(claim.claimKey);
    const items = claim.citationIds.map((id) => resolveGroundingCitation(pack, id));
    const relations = normalizeClaimRelations(
      relationTable[claim.claimKey],
      claim.citationIds,
      claim.claimKey,
    );
    const coverage = classifyClaimCoverage(items, relations);
    if (claim.kind === "factual" && coverage === "insufficient-evidence") {
      throw new Error(`Factual grounded claim ${claim.claimKey} has no supporting evidence`);
    }
    return {
      claimKey: claim.claimKey,
      text: claim.text,
      kind: claim.kind,
      citationIds: Object.freeze([...claim.citationIds]),
      citationRelations: freezeRecord(relations),
      citations: Object.freeze(items.map(toGroundingCitationProjection)),
      coverage,
    } satisfies ValidatedGroundedClaim;
  });
  for (const key of Object.keys(relationTable)) {
    if (!claimKeys.has(key)) throw new Error(`Grounded relation references unknown claim ${key}`);
  }
  const status = classifyAnswerStatus(claims);
  if (answer.status !== undefined && answer.status !== status) {
    throw new Error("Grounded answer status does not match its validated citations");
  }
  assertCitationMarkers(
    answer.answerMarkdown,
    claims,
    pack,
    options.requireCitationMarkers === true,
  );
  return deepFreeze({
    version: GROUNDING_ANSWER_VERSION,
    answerMarkdown: answer.answerMarkdown,
    claims: Object.freeze(claims),
    status,
    packHash: pack.hash,
  });
}

export async function validateGroundedAnswerAsync(
  pack: GroundingPack,
  value: unknown,
  options: GroundedAnswerValidationOptions = {},
): Promise<ValidatedGroundedAnswer> {
  await assertGroundingPack(pack);
  return validateGroundedAnswer(pack, value, options);
}

export const validateGroundedOutput = validateGroundedAnswer;
export const validateGroundedOutputAsync = validateGroundedAnswerAsync;

/** Computes coverage from trusted claim-bound relations, never pack-wide labels. */
export function classifyClaimCoverage(
  items: readonly GroundingPackItem[],
  relations: ReadonlyMap<string, GroundingClaimRelation> | GroundingClaimRelationMap = new Map(),
): GroundingCoverageState {
  const supportingSources = new Set<string>();
  let qualifying = 0;
  let contradicting = 0;
  for (const item of items) {
    const relation =
      relations instanceof Map
        ? relations.get(item.citationId)
        : (relations as GroundingClaimRelationMap)[item.citationId];
    if (relation === "supports") {
      for (const sourceId of item.sourceIds) supportingSources.add(sourceId);
    } else if (relation === "qualifies") {
      qualifying += 1;
    } else if (relation === "contradicts") {
      contradicting += 1;
    }
  }
  if (contradicting > 0 && (supportingSources.size > 0 || qualifying > 0)) {
    return "conflicting-sources";
  }
  if (supportingSources.size >= 2) return "multiple-supporting-sources";
  if (supportingSources.size > 0 || qualifying > 0) return "partial-support";
  if (contradicting > 0) return "conflicting-sources";
  return "insufficient-evidence";
}

function assertValidationOptions(options: GroundedAnswerValidationOptions): void {
  if (options === null || typeof options !== "object" || Array.isArray(options)) {
    throw new Error("Grounded answer validation options are invalid");
  }
  const allowed = new Set([
    "claimRelations",
    "relations",
    "maxCitationsPerClaim",
    "requireCitationMarkers",
  ]);
  if (Object.keys(options as Record<string, unknown>).some((key) => !allowed.has(key))) {
    throw new Error("Grounded answer validation options are invalid");
  }
  if (
    options.requireCitationMarkers !== undefined &&
    typeof options.requireCitationMarkers !== "boolean"
  ) {
    throw new Error("Grounded answer marker option is invalid");
  }
  if (
    options.claimRelations !== undefined &&
    options.relations !== undefined &&
    options.claimRelations !== options.relations
  ) {
    throw new Error("Grounded answer relation tables conflict");
  }
}

function normalizeClaimRelations(
  raw: GroundingClaimRelationMap | readonly GroundingClaimRelationInput[] | undefined,
  citationIds: readonly string[],
  claimKey: string,
): GroundingClaimRelationMap {
  const cited = new Set(citationIds);
  const result: Record<string, GroundingClaimRelation> = {};
  if (raw === undefined) return result;
  if (Array.isArray(raw)) {
    dense(raw, `Grounded claim ${claimKey} relations`);
    const seen = new Set<string>();
    for (const entry of raw) {
      if (!isRecord(entry)) throw new Error("Grounded claim relation is invalid");
      assertExactKeys(entry, ["citationId", "relation"]);
      const citationId = normalizeCitationId(entry.citationId, "Grounded claim relation citation");
      if (!GROUNDING_CLAIM_RELATIONS.includes(entry.relation as GroundingClaimRelation)) {
        throw new Error("Grounded claim relation is invalid");
      }
      if (seen.has(citationId) || !cited.has(citationId)) {
        throw new Error("Grounded claim relation references an invalid citation");
      }
      seen.add(citationId);
      result[citationId] = entry.relation as GroundingClaimRelation;
    }
    return result;
  }
  if (!isRecord(raw)) throw new Error(`Grounding claim ${claimKey} relation is invalid`);
  for (const [citationId, relation] of Object.entries(raw)) {
    const id = normalizeCitationId(citationId, `Grounding claim ${claimKey} relation citation`);
    if (!cited.has(id) || !GROUNDING_CLAIM_RELATIONS.includes(relation as GroundingClaimRelation)) {
      throw new Error(`Grounding claim ${claimKey} relation is invalid`);
    }
    result[id] = relation as GroundingClaimRelation;
  }
  return result;
}

function classifyAnswerStatus(claims: readonly ValidatedGroundedClaim[]): GroundingAnswerStatus {
  if (claims.some((claim) => claim.coverage === "conflicting-sources")) return "conflicting";
  if (claims.length === 0 || claims.every((claim) => claim.coverage === "insufficient-evidence")) {
    return "insufficient";
  }
  return "answer";
}

function assertCitationMarkers(
  markdown: string,
  claims: readonly ValidatedGroundedClaim[],
  pack: GroundingPack,
  requireMarkers: boolean,
): void {
  const claimedIds = new Set(claims.flatMap((claim) => claim.citationIds));
  const seen = new Set<string>();
  for (const match of markdown.matchAll(/\b(?:cite|citation):([0-9]+)\b/gi)) {
    const number = match[1]!;
    if (!/^[1-9][0-9]*$/.test(number)) {
      throw new Error(`Grounded answer marker ${match[0]} is malformed`);
    }
    const id = `cite:${number}`;
    resolveGroundingCitation(pack, id);
    if (!claimedIds.has(id)) {
      throw new Error(`Grounded answer marker ${id} is not bound to a claim`);
    }
    seen.add(id);
  }
  for (const match of markdown.matchAll(/\b(?:cite|citation):([^\s\])}.,;!?]+)/gi)) {
    if (!/^[0-9]+$/.test(match[1]!)) {
      throw new Error(`Grounded answer marker ${match[0]} is malformed`);
    }
  }
  if (requireMarkers) {
    for (const claim of claims) {
      if (
        (claim.kind === "factual" || claim.kind === "interpretive") &&
        !claim.citationIds.some((id) => seen.has(id))
      ) {
        throw new Error(`Grounded claim ${claim.claimKey} has no citation marker`);
      }
    }
  }
}

function normalizeCitationId(value: unknown, label: string): string {
  if (typeof value !== "string" || !/^cite:[1-9][0-9]*$/.test(value) || value.length > 64) {
    throw new Error(`${label} is invalid`);
  }
  return value;
}

function assertExactKeys(value: Record<string, unknown>, keys: readonly string[]): void {
  const expected = new Set(keys);
  const actual = Object.keys(value);
  if (actual.length !== expected.size || actual.some((key) => !expected.has(key))) {
    throw new Error("Grounded claim relation is invalid");
  }
}

function dense(value: readonly unknown[], label: string): void {
  for (let index = 0; index < value.length; index += 1) {
    if (!Object.hasOwn(value, index)) throw new Error(`${label} must be a dense array`);
  }
}

function freezeRecord(value: GroundingClaimRelationMap): GroundingClaimRelationMap {
  return Object.freeze({ ...value });
}

function deepFreeze<T>(value: T): T {
  if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;
  Object.freeze(value);
  for (const child of Object.values(value as Record<string, unknown>)) deepFreeze(child);
  return value;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
